[2024-08-30T06:50:09.338+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-30T06:50:09.356+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v2.second_task manual__2024-08-30T06:50:08.065501+00:00 [queued]>
[2024-08-30T06:50:09.364+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v2.second_task manual__2024-08-30T06:50:08.065501+00:00 [queued]>
[2024-08-30T06:50:09.365+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-08-30T06:50:09.378+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): second_task> on 2024-08-30 06:50:08.065501+00:00
[2024-08-30T06:50:09.387+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1330) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-30T06:50:09.388+0000] {standard_task_runner.py:72} INFO - Started process 1331 to run task
[2024-08-30T06:50:09.387+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v2', 'second_task', 'manual__2024-08-30T06:50:08.065501+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp3f10mtbi']
[2024-08-30T06:50:09.389+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask second_task
[2024-08-30T06:50:09.437+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_v2.second_task manual__2024-08-30T06:50:08.065501+00:00 [running]> on host efc48c282cbe
[2024-08-30T06:50:09.514+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ubeyd' AIRFLOW_CTX_DAG_ID='my_first_dag_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-30T06:50:08.065501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-30T06:50:08.065501+00:00'
[2024-08-30T06:50:09.515+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-30T06:50:09.528+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-30T06:50:09.530+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1']
[2024-08-30T06:50:09.541+0000] {subprocess.py:86} INFO - Output:
[2024-08-30T06:50:09.543+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1
[2024-08-30T06:50:09.543+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-30T06:50:09.572+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-30T06:50:09.572+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v2, task_id=second_task, run_id=manual__2024-08-30T06:50:08.065501+00:00, execution_date=20240830T065008, start_date=20240830T065009, end_date=20240830T065009
[2024-08-30T06:50:09.604+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-30T06:50:09.622+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-30T06:50:09.625+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
